apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    name: {{ .Chart.Name }}-backend
    tier: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}