---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
spec:
  selector:
    matchLabels:
      name: {{ .Chart.Name }}-backend
      tier: backend
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}-backend
        tier: backend
    spec:
      containers:
        - name: backend-container
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.db.secretName }}
          env:
            - name: DB_CERT_PATH
              value: "/etc/ssl/certs/server-ca.crt"
          volumeMounts:
            - name: db-ca-cert-vol
              mountPath: /etc/ssl/certs
              readOnly: true

      volumes:
        - name: db-ca-cert-vol
          secret:
            secretName: {{ .Chart.Name }}-db-ca
            items:
              - key: server-ca.crt
                path: server-ca.crt
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-backend
  minReplicas: {{ .Values.backend.replicaCount.min }}
  maxReplicas: {{ .Values.backend.replicaCount.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.cpuAverageUtilization }}