---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount.min }}
  selector:
    matchLabels:
      name: {{ .Chart.Name }}-frontend
      tier: frontend
  template:
    metadata:
      labels:
        name: {{ .Chart.Name }}-frontend
        tier: frontend
    spec:
      containers:
        - name: frontend-container
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}-frontend
  minReplicas: {{ .Values.frontend.replicaCount.min }}
  maxReplicas: {{ .Values.frontend.replicaCount.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.cpuAverageUtilization }}
