apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: givegift-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Rewrite "/api/<capture>" -> "/<capture>" when proxying to backend-service
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingressExtIP }}.nip.io
      http:
        paths:
          # Any request matching /api/<capture> goes to backend
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: {{ .Values.backend.service.port }}

          # All other requests go to frontend
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ .Values.frontend.service.port }}
