helm:
  parameters:
  - name: image.name
    value: cr.yandex/crplvdacg3tpu0lg6jj7/givegift-backend
    forcestring: true
  - name: image.tag
    value: b80bb19f819b83376547460d3425ad0abcad0829
    forcestring: true
