frontend:
  service:
    port: 80
    type: ClusterIP
  image:
    repository: cr.yandex/crplvdacg3tpu0lg6jj7/givegift-frontend
    tag: b80bb19f819b83376547460d3425ad0abcad0829
    pullPolicy: Always
  replicaCount:
    min: 1
    max: 5
  cpuAverageUtilization: 15
backend:
  service:
    port: 5000
    type: ClusterIP
  image:
    repository: cr.yandex/crplvdacg3tpu0lg6jj7/givegift-backend
    tag: 8381d5ff0e37bd58abbaa4c906dfb3b1ba6173fa
    pullPolicy: Always
  replicaCount:
    min: 1
    max: 5
  cpuAverageUtilization: 15
db:
  localCertPath: C:/Users/AmEl/.postgresql/root.crt
  secretName: givegift-db-secret
ingressExtIP: 158.160.182.170
